#!/usr/bin/env python3

classes = [
    'Object',
    'PathRemap',
    'Performance',
    'Physics2DDirectBodyState',
    'Physics2DDirectBodyStateSW',
    'Physics2DDirectSpaceState',
    'Physics2DServer',
    'Physics2DServerSW',
    'PhysicsDirectBodyState',
    'PhysicsDirectBodyStateSW',
    'PhysicsDirectSpaceState',
    'PhysicsServer',
    'PhysicsServerSW',
    'Reference',
    'RegEx',
    'Resource',
    'ResourceImportMetadata',
    'ResourceInteractiveLoader',
    'RoomBounds',
    'Sample',
    'SampleLibrary',
    'SceneState',
    'Script',
    'Shader',
    'ShaderGraph',
    'Shape',
    'Shape2D',
    'SpatialGizmo',
    'SpatialSound2DServer',
    'SpatialSound2DServerSW',
    'SpatialSoundServer',
    'SpatialSoundServerSW',
    'SphereShape',
    'SpriteFrames',
    'StreamPeer',
    'StreamPeerSSL',
    'StreamPeerTCP',
    'StyleBox',
    'StyleBoxEmpty',
    'StyleBoxFlat',
    'StyleBoxImageMask',
    'StyleBoxTexture',
    'SurfaceTool',
    'TCP_Server',
    'Texture',
    'Theme',
    'TileSet',
    'Translation',
    'TranslationServer',
    'TreeItem',
    'UndoRedo',
    'VideoStream',
    'VideoStreamTheora',
    'VisualServer',
    'WeakRef',
    'World',
    'World2D',
    'XMLParser',
    '_Directory',
    '_File',
    '_Geometry',
    '_Marshalls',
    '_Mutex',
    '_OS',
    '_ResourceLoader',
    '_ResourceSaver',
    '_Semaphore',
    '_Thread',
    'Animation',
    'AtlasTexture',
    'AudioServer',
    'AudioServerSW',
    'AudioStream',
    'AudioStreamMPC',
    'AudioStreamOGGVorbis',
    'AudioStreamOpus',
    'AudioStreamPlayback',
    'AudioStreamSpeex',
    'BakedLight',
    'BitMap',
    'BoxShape',
    'CSharpScript',
    'CanvasItemMaterial',
    'CanvasItemShader',
    'CanvasItemShaderGraph',
    'CapsuleShape',
    'CapsuleShape2D',
    'CircleShape2D',
    'ColorRamp',
    'ConcavePolygonShape',
    'ConcavePolygonShape2D',
    'ConfigFile',
    'ConvexPolygonShape',
    'ConvexPolygonShape2D',
    'CubeMap',
    'Curve2D',
    'Curve3D',
    'DynamicFontData',
    'EditorExportPlugin',
    'EditorImportPlugin',
    'EditorScenePostImport',
    'EditorScript',
    'EditorSelection',
    'EditorSettings',
    'EditorSpatialGizmo',
    'Environment',
    'EventStream',
    'EventStreamChibi',
    'Font',
    'FuncRef',
    'GDFunctionState',
    'GDScript',
    'Globals',
    'HTTPClient',
    'IP',
    'IP_Unix',
    'ImageTexture',
    'Input',
    'InputDefault',
    'InputMap',
    'LargeTexture',
    'LineShape2D',
    'MainLoop',
    'Material',
    'MaterialShader',
    'MaterialShaderGraph',
    'Mesh',
    'MeshDataTool',
    'MeshLibrary',
    'MultiMesh',
    'NavigationMesh',
    'NavigationPolygon',
    'Node',
    'OccluderPolygon2D',
    'PCKPacker',
    'PHashTranslation',
    'PackedDataContainer',
    'PackedDataContainerRef',
    'PackedScene',
    'PacketPeer',
    'PacketPeerStream',
    'PacketPeerUDP',
    'Physics2DShapeQueryParameters',
    'Physics2DShapeQueryResult',
    'Physics2DTestMotionResult',
    'PhysicsShapeQueryParameters',
    'PhysicsShapeQueryResult',
    'PlaneShape',
    'PolygonPathFinder',
    'RayShape',
    'RayShape2D',
    'RectangleShape2D',
    'RenderTargetTexture',
    'ResourcePreloader',
    'SamplePlayer',
    'SceneTree',
    'SegmentShape2D',
    'ShaderMaterial',
    'SoundRoomParams',
    'Spatial',
    'SpatialPlayer',
    'SpatialSamplePlayer',
    'SpatialStreamPlayer',
    'StreamPlayer',
    'Timer',
    'Tween',
    'VehicleWheel',
    'Viewport',
    'VisibilityNotifier',
    'VisualInstance',
    'WorldEnvironment',
    'AnimationPlayer',
    'AnimationTreePlayer',
    'BakedLightInstance',
    'BakedLightSampler',
    'BitmapFont',
    'BoneAttachment',
    'Camera',
    'CanvasItem',
    'CanvasLayer',
    'CollisionObject',
    'CollisionPolygon',
    'CollisionShape',
    'Control',
    'DynamicFont',
    'EditorPlugin',
    'EventPlayer',
    'FixedMaterial',
    'GeometryInstance',
    'GraphEdit',
    'GridMap',
    'HTTPRequest',
    'ImmediateGeometry',
    'InstancePlaceholder',
    'InterpolatedCamera',
    'InverseKinematics',
    'ItemList',
    'Joint',
    'Label',
    'Light',
    'LineEdit',
    'MeshInstance',
    'MultiMeshInstance',
    'Navigation',
    'NavigationMeshInstance',
    'Node2D',
    'OmniLight',
    'Panel',
    'ParallaxBackground',
    'ParallaxLayer',
    'ParticleAttractor2D',
    'Particles',
    'Particles2D',
    'Patch9Frame',
    'Path',
    'Path2D',
    'PathFollow',
    'PathFollow2D',
    'PhysicsBody',
    'PinJoint',
    'Polygon2D',
    'Popup',
    'PopupDialog',
    'PopupMenu',
    'PopupPanel',
    'Portal',
    'Position2D',
    'Position3D',
    'ProximityGroup',
    'Quad',
    'Range',
    'RayCast',
    'RayCast2D',
    'ReferenceFrame',
    'RemoteTransform2D',
    'RichTextLabel',
    'RigidBody',
    'Room',
    'ScrollBar',
    'Separator',
    'Skeleton',
    'Slider',
    'SliderJoint',
    'SoundPlayer2D',
    'SpinBox',
    'SpotLight',
    'Sprite',
    'SpriteBase3D',
    'StaticBody',
    'TabContainer',
    'Tabs',
    'TestCube',
    'TextEdit',
    'TextureFrame',
    'TextureProgress',
    'TileMap',
    'TouchScreenButton',
    'Tree',
    'VScrollBar',
    'VSeparator',
    'VSlider',
    'VehicleBody',
    'VideoPlayer',
    'ViewportSprite',
    'VisibilityEnabler',
    'VisibilityNotifier2D',
    'WindowDialog',
    'YSort',
    'AcceptDialog',
    'AnimatedSprite',
    'AnimatedSprite3D',
    'Area',
    'BackBufferCopy',
    'BaseButton',
    'Button',
    'ButtonArray',
    'Camera2D',
    'CanvasModulate',
    'CheckBox',
    'CheckButton',
    'CollisionObject2D',
    'CollisionPolygon2D',
    'CollisionShape2D',
    'ColorPickerButton',
    'ConeTwistJoint',
    'ConfirmationDialog',
    'Container',
    'DirectionalLight',
    'EditorFileDialog',
    'FileDialog',
    'Generic6DOFJoint',
    'GraphNode',
    'GridContainer',
    'HButtonArray',
    'HScrollBar',
    'HSeparator',
    'HSlider',
    'HingeJoint',
    'Joint2D',
    'KinematicBody',
    'Light2D',
    'LightOccluder2D',
    'LinkButton',
    'MarginContainer',
    'MenuButton',
    'Navigation2D',
    'NavigationPolygonInstance',
    'OptionButton',
    'PanelContainer',
    'PhysicsBody2D',
    'PinJoint2D',
    'ProgressBar',
    'RigidBody2D',
    'SamplePlayer2D',
    'ScrollContainer',
    'SplitContainer',
    'Sprite3D',
    'StaticBody2D',
    'TextureButton',
    'ToolButton',
    'VButtonArray',
    'VSplitContainer',
    'VisibilityEnabler2D',
    'Area2D',
    'BoxContainer',
    'ButtonGroup',
    'CenterContainer',
    'ColorPicker',
    'DampedSpringJoint2D',
    'GrooveJoint2D',
    'HBoxContainer',
    'HSplitContainer',
    'KinematicBody2D',
    'VBoxContainer',
    'DynamicFontData',
    'DynamicFont'
]

paths = {
    'Object': 'core/object.h',
    'Reference': 'core/reference.h',
    'WeakRef': 'core/reference.h',
    'ResourceImportMetadata': 'core/resource.h',
    'Resource': 'core/resource.h',
    'FuncRef': 'core/func_ref.h',
    'StreamPeer': 'core/io/stream_peer.h',
    'StreamPeerTCP': 'core/io/stream_peer_tcp.h',
    'TCP_Server': 'core/io/tcp_server.h',
    'PacketPeer': 'core/io/packet_peer.h',
    'PacketPeerUDP': 'core/io/packet_peer_udp.h',
    'StreamPeerSSL': 'core/io/stream_peer_ssl.h',
    'IP': 'core/io/ip.h',
    'PacketPeerStream': 'core/io/packet_peer.h',
    'MainLoop': 'core/os/main_loop.h',
    'Translation': 'core/translation.h',
    'PHashTranslation': 'core/compressed_translation.h',
    'UndoRedo': 'core/undo_redo.h',
    'HTTPClient': 'core/io/http_client.h',
    'ResourceInteractiveLoader': 'core/io/resource_loader.h',
    '_File': 'core/bind/core_bind.h',
    '_Directory': 'core/bind/core_bind.h',
    '_Thread': 'core/bind/core_bind.h',
    '_Mutex': 'core/bind/core_bind.h',
    '_Semaphore': 'core/bind/core_bind.h',
    'XMLParser': 'core/io/xml_parser.h',
    'ConfigFile': 'core/io/config_file.h',
    'PackedDataContainer': 'core/packed_data_container.h',
    'PackedDataContainerRef': 'core/packed_data_container.h',
    'IP_Unix': 'drivers/unix/ip_unix.h',
    '_Geometry': 'core/bind/core_bind.h',
    '_ResourceLoader': 'core/bind/core_bind.h',
    '_ResourceSaver': 'core/bind/core_bind.h',
    '_OS': 'core/bind/core_bind.h',
    '_Marshalls': 'core/bind/core_bind.h',
    'RegEx': 'drivers/nrex/regex.h',
    'Globals': 'core/globals.h',
    'InputMap': 'core/input_map.h',
    'PathRemap': 'core/path_remap.h',
    'TranslationServer': 'core/translation.h',
    'Performance': 'main/performance.h',
    'VisualServer': 'servers/visual_server.h',
    'AudioServer': 'servers/audio_server.h',
    'AudioServerSW': 'servers/audio/audio_server_sw.h',
    'SpatialSoundServer': 'servers/spatial_sound_server.h',
    'SpatialSoundServerSW': 'servers/spatial_sound/spatial_sound_server_sw.h',
    'SpatialSound2DServer': 'servers/spatial_sound_2d_server.h',
    'SpatialSound2DServerSW': 'servers/spatial_sound_2d/spatial_sound_2d_server_sw.h',
    'PhysicsServer': 'servers/physics_server.h',
    'PhysicsServerSW': 'servers/physics/physics_server_sw.h',
    'PhysicsDirectBodyState': 'servers/physics_server.h',
    'PhysicsDirectBodyStateSW': 'servers/physics/body_sw.h',
    'Physics2DServer': 'servers/physics_2d_server.h',
    'Physics2DServerSW': 'servers/physics_2d/physics_2d_server_sw.h',
    'Physics2DDirectBodyState': 'servers/physics_2d_server.h',
    'Physics2DDirectBodyStateSW': 'servers/physics_2d/body_2d_sw.h',
    'Input': 'core/os/input.h',
    'InputDefault': 'main/input_default.h',
    'Theme': 'scene/resources/theme.h',
    'Font': 'scene/resources/font.h',
    'BitmapFont': 'scene/resources/font.h',
    'Texture': 'scene/resources/texture.h',
    'ImageTexture': 'scene/resources/texture.h',
    'StyleBox': 'scene/resources/style_box.h',
    'StyleBoxTexture': 'scene/resources/style_box.h',
    'StyleBoxEmpty': 'scene/resources/style_box.h',
    'Shader': 'scene/resources/shader.h',
    'Node': 'scene/main/node.h',
    'InstancePlaceholder': 'scene/main/instance_placeholder.h',
    'Viewport': 'scene/main/viewport.h',
    'RenderTargetTexture': 'scene/main/viewport.h',
    'HTTPRequest': 'scene/main/http_request.h',
    'Timer': 'scene/main/timer.h',
    'CanvasLayer': 'scene/main/canvas_layer.h',
    'CanvasItem': 'scene/2d/canvas_item.h',
    'Node2D': 'scene/2d/node_2d.h',
    'CanvasModulate': 'scene/2d/canvas_modulate.h',
    'ResourcePreloader': 'scene/main/resource_preloader.h',
    'Control': 'scene/gui/control.h',
    'Container': 'scene/gui/container.h',
    'BoxContainer': 'scene/gui/box_container.h',
    'ButtonGroup': 'scene/gui/button_group.h',
    'BaseButton': 'scene/gui/base_button.h',
    'Button': 'scene/gui/button.h',
    'Label': 'scene/gui/label.h',
    'Range': 'scene/gui/range.h',
    'ScrollBar': 'scene/gui/scroll_bar.h',
    'HScrollBar': 'scene/gui/scroll_bar.h',
    'VScrollBar': 'scene/gui/scroll_bar.h',
    'ProgressBar': 'scene/gui/progress_bar.h',
    'Slider': 'scene/gui/slider.h',
    'HSlider': 'scene/gui/slider.h',
    'VSlider': 'scene/gui/slider.h',
    'Popup': 'scene/gui/popup.h',
    'PopupPanel': 'scene/gui/popup.h',
    'MenuButton': 'scene/gui/menu_button.h',
    'CheckBox': 'scene/gui/check_box.h',
    'CheckButton': 'scene/gui/check_button.h',
    'ToolButton': 'scene/gui/tool_button.h',
    'LinkButton': 'scene/gui/link_button.h',
    'Panel': 'scene/gui/panel.h',
    'TextureFrame': 'scene/gui/texture_frame.h',
    'Patch9Frame': 'scene/gui/patch_9_frame.h',
    'TabContainer': 'scene/gui/tab_container.h',
    'Tabs': 'scene/gui/tabs.h',
    'Separator': 'scene/gui/separator.h',
    'HSeparator': 'scene/gui/separator.h',
    'VSeparator': 'scene/gui/separator.h',
    'TextureButton': 'scene/gui/texture_button.h',
    'HBoxContainer': 'scene/gui/box_container.h',
    'VBoxContainer': 'scene/gui/box_container.h',
    'GridContainer': 'scene/gui/grid_container.h',
    'CenterContainer': 'scene/gui/center_container.h',
    'ScrollContainer': 'scene/gui/scroll_container.h',
    'PanelContainer': 'scene/gui/panel_container.h',
    'SplitContainer': 'scene/gui/split_container.h',
    'HSplitContainer': 'scene/gui/split_container.h',
    'VSplitContainer': 'scene/gui/split_container.h',
    'GraphNode': 'scene/gui/graph_node.h',
    'GraphEdit': 'scene/gui/graph_edit.h',
    'ButtonArray': 'scene/gui/button_array.h',
    'HButtonArray': 'scene/gui/button_array.h',
    'VButtonArray': 'scene/gui/button_array.h',
    'TextureProgress': 'scene/gui/texture_progress.h',
    'ItemList': 'scene/gui/item_list.h',
    'WindowDialog': 'scene/gui/dialogs.h',
    'AcceptDialog': 'scene/gui/dialogs.h',
    'ConfirmationDialog': 'scene/gui/dialogs.h',
    'FileDialog': 'scene/gui/file_dialog.h',
    'LineEdit': 'scene/gui/line_edit.h',
    'PopupMenu': 'scene/gui/popup_menu.h',
    'Tree': 'scene/gui/tree.h',
    'TextEdit': 'scene/gui/text_edit.h',
    'TreeItem': 'scene/gui/tree.h',
    'OptionButton': 'scene/gui/option_button.h',
    'SpinBox': 'scene/gui/spin_box.h',
    'ReferenceFrame': 'scene/gui/reference_frame.h',
    'ColorPicker': 'scene/gui/color_picker.h',
    'ColorPickerButton': 'scene/gui/color_picker.h',
    'RichTextLabel': 'scene/gui/rich_text_label.h',
    'PopupDialog': 'scene/gui/dialogs.h',
    'VideoPlayer': 'scene/gui/video_player.h',
    'MarginContainer': 'scene/gui/margin_container.h',
    'Spatial': 'scene/3d/spatial.h',
    'Skeleton': 'scene/3d/skeleton.h',
    'AnimationPlayer': 'scene/animation/animation_player.h',
    'Tween': 'scene/animation/tween.h',
    'BoneAttachment': 'scene/3d/bone_attachment.h',
    'VisualInstance': 'scene/3d/visual_instance.h',
    'Camera': 'scene/3d/camera.h',
    'InterpolatedCamera': 'scene/3d/interpolated_camera.h',
    'GeometryInstance': 'scene/3d/visual_instance.h',
    'TestCube': 'scene/3d/test_cube.h',
    'MeshInstance': 'scene/3d/mesh_instance.h',
    'ImmediateGeometry': 'scene/3d/immediate_geometry.h',
    'SpriteBase3D': 'scene/3d/sprite_3d.h',
    'Sprite3D': 'scene/3d/sprite_3d.h',
    'AnimatedSprite3D': 'scene/3d/sprite_3d.h',
    'Light': 'scene/3d/light.h',
    'DirectionalLight': 'scene/3d/light.h',
    'OmniLight': 'scene/3d/light.h',
    'SpotLight': 'scene/3d/light.h',
    'AnimationTreePlayer': 'scene/animation/animation_tree_player.h',
    'Portal': 'scene/3d/portal.h',
    'Particles': 'scene/3d/particles.h',
    'Position3D': 'scene/3d/position_3d.h',
    'Quad': 'scene/3d/quad.h',
    'NavigationMeshInstance': 'scene/3d/navigation_mesh.h',
    'NavigationMesh': 'scene/3d/navigation_mesh.h',
    'Navigation': 'scene/3d/navigation.h',
    'CollisionObject': 'scene/3d/collision_object.h',
    'PhysicsBody': 'scene/3d/physics_body.h',
    'StaticBody': 'scene/3d/physics_body.h',
    'RigidBody': 'scene/3d/physics_body.h',
    'KinematicBody': 'scene/3d/physics_body.h',
    'VehicleBody': 'scene/3d/vehicle_body.h',
    'VehicleWheel': 'scene/3d/vehicle_body.h',
    'Area': 'scene/3d/area.h',
    'ProximityGroup': 'scene/3d/proximity_group.h',
    'CollisionShape': 'scene/3d/body_shape.h',
    'CollisionPolygon': 'scene/3d/collision_polygon.h',
    'RayCast': 'scene/3d/ray_cast.h',
    'MultiMeshInstance': 'scene/3d/multimesh_instance.h',
    'Room': 'scene/3d/room_instance.h',
    'Curve3D': 'scene/resources/curve.h',
    'Path': 'scene/3d/path.h',
    'PathFollow': 'scene/3d/path.h',
    'VisibilityNotifier': 'scene/3d/visibility_notifier.h',
    'VisibilityEnabler': 'scene/3d/visibility_notifier.h',
    'BakedLightInstance': 'scene/3d/baked_light_instance.h',
    'BakedLightSampler': 'scene/3d/baked_light_instance.h',
    'WorldEnvironment': 'scene/3d/scenario_fx.h',
    'Joint': 'scene/3d/physics_joint.h',
    'PinJoint': 'scene/3d/physics_joint.h',
    'HingeJoint': 'scene/3d/physics_joint.h',
    'SliderJoint': 'scene/3d/physics_joint.h',
    'ConeTwistJoint': 'scene/3d/physics_joint.h',
    'Generic6DOFJoint': 'scene/3d/physics_joint.h',
    'SpatialPlayer': 'scene/3d/spatial_player.h',
    'SpatialSamplePlayer': 'scene/3d/spatial_sample_player.h',
    'SpatialStreamPlayer': 'scene/3d/spatial_stream_player.h',
    'SoundRoomParams': 'scene/audio/sound_room_params.h',
    'MeshLibrary': 'scene/resources/mesh_library.h',
    'SamplePlayer': 'scene/audio/sample_player.h',
    'StreamPlayer': 'scene/audio/stream_player.h',
    'EventPlayer': 'scene/audio/event_player.h',
    'CanvasItemMaterial': 'scene/2d/canvas_item.h',
    'Particles2D': 'scene/2d/particles_2d.h',
    'ParticleAttractor2D': 'scene/2d/particles_2d.h',
    'Sprite': 'scene/2d/sprite.h',
    'ViewportSprite': 'scene/2d/sprite.h',
    'SpriteFrames': 'scene/2d/animated_sprite.h',
    'AnimatedSprite': 'scene/2d/animated_sprite.h',
    'Position2D': 'scene/2d/position_2d.h',
    'CollisionObject2D': 'scene/2d/collision_object_2d.h',
    'PhysicsBody2D': 'scene/2d/physics_body_2d.h',
    'StaticBody2D': 'scene/2d/physics_body_2d.h',
    'RigidBody2D': 'scene/2d/physics_body_2d.h',
    'KinematicBody2D': 'scene/2d/physics_body_2d.h',
    'Area2D': 'scene/2d/area_2d.h',
    'CollisionShape2D': 'scene/2d/collision_shape_2d.h',
    'CollisionPolygon2D': 'scene/2d/collision_polygon_2d.h',
    'RayCast2D': 'scene/2d/ray_cast_2d.h',
    'VisibilityNotifier2D': 'scene/2d/visibility_notifier_2d.h',
    'VisibilityEnabler2D': 'scene/2d/visibility_notifier_2d.h',
    'Polygon2D': 'scene/2d/polygon_2d.h',
    'Light2D': 'scene/2d/light_2d.h',
    'LightOccluder2D': 'scene/2d/light_occluder_2d.h',
    'OccluderPolygon2D': 'scene/2d/light_occluder_2d.h',
    'YSort': 'scene/2d/y_sort.h',
    'BackBufferCopy': 'scene/2d/back_buffer_copy.h',
    'Camera2D': 'scene/2d/camera_2d.h',
    'Joint2D': 'scene/2d/joints_2d.h',
    'PinJoint2D': 'scene/2d/joints_2d.h',
    'GrooveJoint2D': 'scene/2d/joints_2d.h',
    'DampedSpringJoint2D': 'scene/2d/joints_2d.h',
    'TileSet': 'scene/resources/tile_set.h',
    'TileMap': 'scene/2d/tile_map.h',
    'ParallaxBackground': 'scene/2d/parallax_background.h',
    'ParallaxLayer': 'scene/2d/parallax_layer.h',
    'SoundPlayer2D': 'scene/2d/sound_player_2d.h',
    'SamplePlayer2D': 'scene/2d/sample_player_2d.h',
    'TouchScreenButton': 'scene/2d/screen_button.h',
    'RemoteTransform2D': 'scene/2d/remote_transform_2d.h',
    'ShaderGraph': 'scene/resources/shader_graph.h',
    'CanvasItemShader': 'scene/resources/shader.h',
    'CanvasItemShaderGraph': 'scene/resources/shader_graph.h',
    'Mesh': 'scene/resources/mesh.h',
    'Material': 'scene/resources/material.h',
    'FixedMaterial': 'scene/resources/material.h',
    'ShaderMaterial': 'scene/resources/material.h',
    'RoomBounds': 'scene/resources/room.h',
    'MaterialShaderGraph': 'scene/resources/shader_graph.h',
    'MaterialShader': 'scene/resources/shader.h',
    'MultiMesh': 'scene/resources/multimesh.h',
    'Shape': 'scene/resources/shape.h',
    'RayShape': 'scene/resources/ray_shape.h',
    'SphereShape': 'scene/resources/sphere_shape.h',
    'BoxShape': 'scene/resources/box_shape.h',
    'CapsuleShape': 'scene/resources/capsule_shape.h',
    'PlaneShape': 'scene/resources/plane_shape.h',
    'ConvexPolygonShape': 'scene/resources/convex_polygon_shape.h',
    'ConcavePolygonShape': 'scene/resources/concave_polygon_shape.h',
    'SurfaceTool': 'scene/resources/surface_tool.h',
    'MeshDataTool': 'scene/resources/mesh_data_tool.h',
    'BakedLight': 'scene/resources/baked_light.h',
    'World': 'scene/resources/world.h',
    'Environment': 'scene/resources/environment.h',
    'World2D': 'scene/resources/world_2d.h',
    'AtlasTexture': 'scene/resources/texture.h',
    'LargeTexture': 'scene/resources/texture.h',
    'CubeMap': 'scene/resources/texture.h',
    'Animation': 'scene/resources/animation.h',
    'StyleBoxFlat': 'scene/resources/style_box.h',
    'StyleBoxImageMask': 'scene/resources/style_box.h',
    'PolygonPathFinder': 'scene/resources/polygon_path_finder.h',
    'BitMap': 'scene/resources/bit_mask.h',
    'ColorRamp': 'scene/resources/color_ramp.h',
    'Sample': 'scene/resources/sample.h',
    'SampleLibrary': 'scene/resources/sample_library.h',
    'AudioStream': 'scene/resources/audio_stream.h',
    'AudioStreamPlayback': 'scene/resources/audio_stream.h',
    'VideoStream': 'scene/resources/video_stream.h',
    'Shape2D': 'scene/resources/shape_2d.h',
    'LineShape2D': 'scene/resources/shape_line_2d.h',
    'SegmentShape2D': 'scene/resources/segment_shape_2d.h',
    'RayShape2D': 'scene/resources/segment_shape_2d.h',
    'CircleShape2D': 'scene/resources/circle_shape_2d.h',
    'RectangleShape2D': 'scene/resources/rectangle_shape_2d.h',
    'CapsuleShape2D': 'scene/resources/capsule_shape_2d.h',
    'ConvexPolygonShape2D': 'scene/resources/convex_polygon_shape_2d.h',
    'ConcavePolygonShape2D': 'scene/resources/concave_polygon_shape_2d.h',
    'Curve2D': 'scene/resources/curve.h',
    'Path2D': 'scene/2d/path_2d.h',
    'PathFollow2D': 'scene/2d/path_2d.h',
    'Navigation2D': 'scene/2d/navigation2d.h',
    'NavigationPolygon': 'scene/2d/navigation_polygon.h',
    'NavigationPolygonInstance': 'scene/2d/navigation_polygon.h',
    'SceneState': 'scene/resources/packed_scene.h',
    'PackedScene': 'scene/resources/packed_scene.h',
    'SceneTree': 'scene/main/scene_main_loop.h',
    'Physics2DDirectSpaceState': 'servers/physics_2d_server.h',
    'Physics2DShapeQueryResult': 'servers/physics_2d_server.h',
    'Physics2DTestMotionResult': 'servers/physics_2d_server.h',
    'Physics2DShapeQueryParameters': 'servers/physics_2d_server.h',
    'PhysicsShapeQueryParameters': 'servers/physics_server.h',
    'PhysicsDirectSpaceState': 'servers/physics_server.h',
    'PhysicsShapeQueryResult': 'servers/physics_server.h',
    'EditorPlugin': 'tools/editor/editor_plugin.h',
    'EditorImportPlugin': 'tools/editor/editor_import_export.h',
    'EditorExportPlugin': 'tools/editor/editor_import_export.h',
    'EditorScenePostImport': 'tools/editor/io_plugins/editor_scene_import_plugin.h',
    'EditorScript': 'tools/editor/editor_run_script.h',
    'EditorSelection': 'tools/editor/editor_data.h',
    'EditorFileDialog': 'tools/editor/editor_file_dialog.h',
    'EditorSettings': 'tools/editor/editor_settings.h',
    'SpatialGizmo': 'scene/3d/spatial.h',
    'EditorSpatialGizmo': 'tools/editor/spatial_editor_gizmos.h',
    'PCKPacker': 'tools/pck/pck_packer.h',
    'InverseKinematics': 'modules/ik/ik.h',
    'GridMap': 'modules/gridmap/grid_map.h',
    'Script': 'core/script_language.h',
    'GDScript': 'modules/gdscript/gd_script.h',
    'GDFunctionState': 'modules/gdscript/gd_script.h',
    'AudioStreamOGGVorbis': 'drivers/vorbis/audio_stream_ogg_vorbis.h',
    'AudioStreamOpus': 'drivers/opus/audio_stream_opus.h',
    'AudioStreamSpeex': 'drivers/speex/audio_stream_speex.h',
    'AudioStreamMPC': 'drivers/mpc/audio_stream_mpc.h',
    'VideoStreamTheora': 'drivers/theora/video_stream_theora.h',
    'EventStream': 'scene/resources/event_stream.h',
    'EventStreamChibi': 'drivers/chibi/event_stream_chibi.h',
    'GDNativeClass': 'modules/gdscript/gd_script.h',
    'Physics2DDirectSpaceStateSW': 'servers/physics_2d/space_2d_sw.h',
    'PhysicsDirectSpaceStateSW': 'servers/physics/space_sw.h',
    'EditorFileSystemDirectory': 'tools/editor/editor_file_system.h',
    'EditorFileSystem': 'tools/editor/editor_file_system.h',
    'EditorImportExport': 'tools/editor/editor_import_export.h',
    'EditorExportPlatform': 'tools/editor/editor_import_export.h',
    'EditorExportPlatformPC': 'tools/editor/editor_import_export.h',
    'EditorExportPlatformBB10': 'platform/bb10/export/export.cpp',
    'EditorExportPlatformJavaScript': 'platform/javascript/export/export.cpp',
    'EditorExportPlatformAndroid': 'platform/android/export/export.cpp',
    'EditorExportPlatformOSX': 'platform/osx/export/export.cpp',
    'EditorResourcePreview': 'tools/editor/editor_resource_preview.h',
    'ProgressDialog': 'tools/editor/progress_dialog.h',
    'EditorRunNative': 'tools/editor/editor_run_native.h',
    'BackgroundProgress': 'tools/editor/progress_dialog.h',
    'EditorNameDialog': 'tools/editor/editor_name_dialog.h',
    'SceneTreeEditor': 'tools/editor/scene_tree_editor.h',
    'CreateDialog': 'tools/editor/create_dialog.h',
    'GroupsEditor': 'tools/editor/groups_editor.h',
    'SceneTreeDialog': 'tools/editor/scene_tree_editor.h',
    'CustomPropertyEditor': 'tools/editor/property_editor.h',
    'PropertyEditor': 'tools/editor/property_editor.h',
    'ConnectDialogBinds': 'tools/editor/connections_dialog.cpp',
    'ConnectDialog': 'tools/editor/connections_dialog.h',
    'ConnectionsDialog': 'tools/editor/connections_dialog.h',
    'ScriptCreateDialog': 'tools/editor/script_create_dialog.h',
    'ReparentDialog': 'tools/editor/reparent_dialog.h',
    'EditorSubScene': 'tools/editor/editor_sub_scene.h',
    'SceneTreeDock': 'tools/editor/scene_tree_dock.h',
    'EditorPath': 'tools/editor/editor_path.h',
    'DependencyEditor': 'tools/editor/dependency_editor.h',
    'DependencyEditorOwners': 'tools/editor/dependency_editor.h',
    'DependencyRemoveDialog': 'tools/editor/dependency_editor.h',
    'EditorDirDialog': 'tools/editor/editor_dir_dialog.h',
    'ScenesDock': 'tools/editor/scenes_dock.h',
    'EditorLog': 'tools/editor/editor_log.h',
    'CallDialogParams': 'tools/editor/call_dialog.cpp',
    'CallDialog': 'tools/editor/call_dialog.h',
    'OrphanResourcesDialog': 'tools/editor/dependency_editor.h',
    'ProjectExport': 'tools/editor/project_export.h',
    'ProjectExportDialog': 'tools/editor/project_export.h',
    'DependencyErrorDialog': 'tools/editor/dependency_editor.h',
    'SectionedPropertyEditorFilter': 'tools/editor/property_editor.cpp',
    'SectionedPropertyEditor': 'tools/editor/property_editor.h',
    'EditorSettingsDialog': 'tools/editor/settings_config_dialog.h',
    'EditorPluginSettings': 'tools/editor/editor_plugin_settings.h',
    'ProjectSettings': 'tools/editor/project_settings.h',
    'ImportSettingsDialog': 'tools/editor/import_settings.h',
    'RunSettingsDialog': 'tools/editor/run_settings_dialog.h',
    'EditorReImportDialog': 'tools/editor/editor_reimport_dialog.h',
    'EditorFileServer': 'tools/editor/fileserver/editor_file_server.h',
    'EditorImportTextureOptions': 'tools/editor/io_plugins/editor_texture_import_plugin.h',
    'EditorTextureImportDialog': 'tools/editor/io_plugins/editor_texture_import_plugin.cpp',
    'EditorTextureImportPlugin': 'tools/editor/io_plugins/editor_texture_import_plugin.h',
    'EditorImportAnimationOptions': 'tools/editor/io_plugins/editor_scene_import_plugin.cpp',
    'EditorSceneImportDialog': 'tools/editor/io_plugins/editor_scene_import_plugin.cpp',
    'EditorSceneImportPlugin': 'tools/editor/io_plugins/editor_scene_import_plugin.h',
    'EditorSceneImporter': 'tools/editor/io_plugins/editor_scene_import_plugin.h',
    'EditorSceneImporterCollada': 'tools/editor/io_plugins/editor_import_collada.h',
    '_EditorMeshImportOptions': 'tools/editor/io_plugins/editor_mesh_import_plugin.cpp',
    'EditorMeshImportDialog': 'tools/editor/io_plugins/editor_mesh_import_plugin.cpp',
    'EditorMeshImportPlugin': 'tools/editor/io_plugins/editor_mesh_import_plugin.h',
    'EditorLineEditFileChooser': 'tools/editor/editor_file_dialog.h',
    '_EditorFontImportOptions': 'tools/editor/io_plugins/editor_font_import_plugin.cpp',
    'EditorFontImportDialog': 'tools/editor/io_plugins/editor_font_import_plugin.cpp',
    'EditorFontImportPlugin': 'tools/editor/io_plugins/editor_font_import_plugin.h',
    '_EditorSampleImportOptions': 'tools/editor/io_plugins/editor_sample_import_plugin.cpp',
    'EditorSampleImportDialog': 'tools/editor/io_plugins/editor_sample_import_plugin.cpp',
    'EditorSampleImportPlugin': 'tools/editor/io_plugins/editor_sample_import_plugin.h',
    'EditorTranslationImportDialog': 'tools/editor/io_plugins/editor_translation_import_plugin.cpp',
    'EditorTranslationImportPlugin': 'tools/editor/io_plugins/editor_translation_import_plugin.h',
    'EditorTextureExportPlugin': 'tools/editor/io_plugins/editor_texture_import_plugin.h',
    'EditorSampleExportPlugin': 'tools/editor/io_plugins/editor_sample_import_plugin.h',
    'EditorSceneExportPlugin': 'tools/editor/io_plugins/editor_export_scene.h',
    'AnimationKeyEdit': 'tools/editor/animation_editor.cpp',
    'AnimationCurveEdit': 'tools/editor/animation_editor.cpp',
    'AnimationKeyEditor': 'tools/editor/animation_editor.h',
    'AnimationPlayerEditor': 'tools/editor/plugins/animation_player_editor_plugin.h',
    'AnimationPlayerEditorPlugin': 'tools/editor/plugins/animation_player_editor_plugin.h',
    'SnapDialog': 'tools/editor/plugins/canvas_item_editor_plugin.cpp',
    'CanvasItemEditor': 'tools/editor/plugins/canvas_item_editor_plugin.h',
    'CanvasItemEditorPlugin': 'tools/editor/plugins/canvas_item_editor_plugin.h',
    'SpatialEditorViewport': 'tools/editor/plugins/spatial_editor_plugin.h',
    'SpatialEditor': 'tools/editor/plugins/spatial_editor_plugin.h',
    'SpatialEditorPlugin': 'tools/editor/plugins/spatial_editor_plugin.h',
    'FindReplaceDialog': 'tools/editor/code_editor.h',
    'GotoLineDialog': 'tools/editor/code_editor.h',
    'ScriptEditorDebuggerVariables': 'tools/editor/script_editor_debugger.cpp',
    'ScriptEditorDebugger': 'tools/editor/script_editor_debugger.h',
    'ScriptEditorQuickOpen': 'tools/editor/plugins/script_editor_plugin.h',
    'EditorHelpSearch': 'tools/editor/editor_help.h',
    'EditorHelpIndex': 'tools/editor/editor_help.h',
    'ScriptEditor': 'tools/editor/plugins/script_editor_plugin.h',
    'ScriptEditorPlugin': 'tools/editor/plugins/script_editor_plugin.h',
    'GraphEditFilter': 'scene/gui/graph_edit.h',
    'ShaderGraphView': 'tools/editor/plugins/shader_graph_editor_plugin.h',
    'ShaderGraphEditor': 'tools/editor/plugins/shader_graph_editor_plugin.h',
    'ShaderGraphEditorPlugin': 'tools/editor/plugins/shader_graph_editor_plugin.h',
    'CodeTextEditor': 'tools/editor/code_editor.h',
    'ShaderTextEditor': 'tools/editor/plugins/shader_editor_plugin.h',
    'ShaderEditor': 'tools/editor/plugins/shader_editor_plugin.h',
    'ShaderEditorPlugin': 'tools/editor/plugins/shader_editor_plugin.h',
    'CameraEditorPlugin': 'tools/editor/plugins/camera_editor_plugin.h',
    'SampleEditor': 'tools/editor/plugins/sample_editor_plugin.h',
    'SampleEditorPlugin': 'tools/editor/plugins/sample_editor_plugin.h',
    'SampleLibraryEditor': 'tools/editor/plugins/sample_library_editor_plugin.h',
    'SampleLibraryEditorPlugin': 'tools/editor/plugins/sample_library_editor_plugin.h',
    'ThemeEditor': 'tools/editor/plugins/theme_editor_plugin.h',
    'ThemeEditorPlugin': 'tools/editor/plugins/theme_editor_plugin.h',
    'MultiMeshEditor': 'tools/editor/plugins/multimesh_editor_plugin.h',
    'MultiMeshEditorPlugin': 'tools/editor/plugins/multimesh_editor_plugin.h',
    'MeshInstanceEditor': 'tools/editor/plugins/mesh_editor_plugin.h',
    'MeshInstanceEditorPlugin': 'tools/editor/plugins/mesh_editor_plugin.h',
    'AnimationTreeEditor': 'tools/editor/plugins/animation_tree_editor_plugin.h',
    'AnimationTreeEditorPlugin': 'tools/editor/plugins/animation_tree_editor_plugin.h',
    'SamplePlayerEditor': 'tools/editor/plugins/sample_player_editor_plugin.h',
    'SamplePlayerEditorPlugin': 'tools/editor/plugins/sample_player_editor_plugin.h',
    'MeshLibraryEditor': 'tools/editor/plugins/cube_grid_theme_editor_plugin.h',
    'MeshLibraryEditorPlugin': 'tools/editor/plugins/cube_grid_theme_editor_plugin.h',
    'StreamEditor': 'tools/editor/plugins/stream_editor_plugin.h',
    'StreamEditorPlugin': 'tools/editor/plugins/stream_editor_plugin.h',
    'StyleBoxEditor': 'tools/editor/plugins/style_box_editor_plugin.h',
    'StyleBoxEditorPlugin': 'tools/editor/plugins/style_box_editor_plugin.h',
    'ParticlesEditor': 'tools/editor/plugins/particles_editor_plugin.h',
    'ParticlesEditorPlugin': 'tools/editor/plugins/particles_editor_plugin.h',
    'ResourcePreloaderEditor': 'tools/editor/plugins/resource_preloader_editor_plugin.h',
    'ResourcePreloaderEditorPlugin': 'tools/editor/plugins/resource_preloader_editor_plugin.h',
    'ItemListEditor': 'tools/editor/plugins/item_list_editor_plugin.h',
    'ItemListPlugin': 'tools/editor/plugins/item_list_editor_plugin.h',
    'ItemListOptionButtonPlugin': 'tools/editor/plugins/item_list_editor_plugin.h',
    'ItemListPopupMenuPlugin': 'tools/editor/plugins/item_list_editor_plugin.h',
    'ItemListEditorPlugin': 'tools/editor/plugins/item_list_editor_plugin.h',
    'CollisionPolygonEditor': 'tools/editor/plugins/collision_polygon_editor_plugin.h',
    'CollisionPolygonEditorPlugin': 'tools/editor/plugins/collision_polygon_editor_plugin.h',
    'CollisionPolygon2DEditor': 'tools/editor/plugins/collision_polygon_2d_editor_plugin.h',
    'CollisionPolygon2DEditorPlugin': 'tools/editor/plugins/collision_polygon_2d_editor_plugin.h',
    'TileSetEditor': 'tools/editor/plugins/tile_set_editor_plugin.h',
    'TileSetEditorPlugin': 'tools/editor/plugins/tile_set_editor_plugin.h',
    'TileMapEditor': 'tools/editor/plugins/tile_map_editor_plugin.h',
    'TileMapEditorPlugin': 'tools/editor/plugins/tile_map_editor_plugin.h',
    'SpriteFramesEditor': 'tools/editor/plugins/sprite_frames_editor_plugin.h',
    'SpriteFramesEditorPlugin': 'tools/editor/plugins/sprite_frames_editor_plugin.h',
    'SpriteRegionEditor': 'tools/editor/plugins/sprite_region_editor_plugin.h',
    'SpriteRegionEditorPlugin': 'tools/editor/plugins/sprite_region_editor_plugin.h',
    'Particles2DEditorPlugin': 'tools/editor/plugins/particles_2d_editor_plugin.h',
    'Path2DEditor': 'tools/editor/plugins/path_2d_editor_plugin.h',
    'Path2DEditorPlugin': 'tools/editor/plugins/path_2d_editor_plugin.h',
    'PathEditorPlugin': 'tools/editor/plugins/path_editor_plugin.h',
    'BakedLightEditor': 'tools/editor/plugins/baked_light_editor_plugin.h',
    'BakedLightEditorPlugin': 'tools/editor/plugins/baked_light_editor_plugin.h',
    'Polygon2DEditor': 'tools/editor/plugins/polygon_2d_editor_plugin.h',
    'Polygon2DEditorPlugin': 'tools/editor/plugins/polygon_2d_editor_plugin.h',
    'LightOccluder2DEditor': 'tools/editor/plugins/light_occluder_2d_editor_plugin.h',
    'LightOccluder2DEditorPlugin': 'tools/editor/plugins/light_occluder_2d_editor_plugin.h',
    'NavigationPolygonEditor': 'tools/editor/plugins/navigation_polygon_editor_plugin.h',
    'NavigationPolygonEditorPlugin': 'tools/editor/plugins/navigation_polygon_editor_plugin.h',
    'ColorRampEdit': 'scene/gui/color_ramp_edit.h',
    'ColorRampEditorPlugin': 'tools/editor/plugins/color_ramp_editor_plugin.h',
    'CollisionShape2DEditor': 'tools/editor/plugins/collision_shape_2d_editor_plugin.h',
    'CollisionShape2DEditorPlugin': 'tools/editor/plugins/collision_shape_2d_editor_plugin.h',
    'CodeCompletionServer': 'modules/autocomplete_service/code_completion_server.h',
    'CodeCompletionService': 'modules/autocomplete_service/code_completion_service.h',
    'CompletionServicePlugin': 'modules/autocomplete_service/completion_service_plugin.h',
    'GridMapEditor': 'modules/gridmap/grid_map_editor_plugin.h',
    'GridMapEditorPlugin': 'modules/gridmap/grid_map_editor_plugin.h',
    'EditorResourcePreviewGenerator': 'tools/editor/editor_resource_preview.h',
    'EditorQuickOpen': 'tools/editor/quick_open.h',
    'EditorExportGDScript': 'modules/gdscript/register_types.cpp',
    'ScriptTextEditor': 'tools/editor/plugins/script_editor_plugin.h',
    'EditorHelp': 'tools/editor/editor_help.h',
    'EditorNode': 'tools/editor/editor_node.h',
    'DynamicFontData': 'scene/resources/dynamic_font.h',
    'DynamicFont': 'scene/resources/dynamic_font.h',
    'CSharpScript': 'modules/csharp/csharp_script.h',
}

paths_final = []

for c in classes:
    path = paths[c]
    if not path in paths_final:
        paths_final.append(path)

with open('includes.txt', 'w', encoding='utf-8') as f:
    f.seek(0)
    for line in paths_final:
        f.write('#include \"' + line + '\"\n')
    f.truncate()
    f.close()
