#!/usr/bin/env python

Import('env')

env.add_source_files(env.modules_sources, '*.cpp')
env.add_source_files(env.modules_sources, 'mono_wrapper/*.cpp')
env.add_source_files(env.modules_sources, 'utils/*.cpp')
env.add_source_files(env.modules_sources, 'utils/tinyxml2/tinyxml2.cpp')

vars = Variables()
vars.Add(BoolVariable('mono_glue', 'Build with the mono glue code', True))
vars.Update(env)

# Glue sources
if env['mono_glue']:
    env.add_source_files(env.modules_sources, 'bindings/mono_glue.cpp')
else:
    env.Append(CPPDEFINES = [ 'MONO_GLUE_DISABLED' ])

if ARGUMENTS.get('yolo_copy', False):
    env.Append(CPPDEFINES = [ 'YOLO_COPY' ])
